#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm --reorder-monitors eDP-1 DP-1-1 DP-1-2 


bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap           4
bspc config top_padding          36
bspc config left_padding         12
bspc config right_padding        12
bspc config bottom_padding       8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

feh --randomize --bg-fill $HOME/Pictures/Wallpapers/ &
polybar &
dropbox &
rofi-gpaste -c &
picom -b &